### ISSUE TITLE
识别率。。。

### ISSUE THREAD

**Issue by Initial-heart-1** [mzdluo123/AntiSetu#5]
![bug](https://i0.hdslb.com/bfs/album/60edb7ee042e40f6c85767d24573b2b2dfd04c7e.png)

**Comment by Initial-heart-1** [comment]
个人建议，提供使用第三方 API 识别的选项，不然这太难受了
同时提供统计以便携的管理用量
我是five，交不起pr
另外，API 推荐腾讯云，鉴黄我谁都不服就服tx

**Comment by mzdluo123** [comment]
已有别的项目实现了使用在线api识别，可以去使用那些项目来满足你的需求，本项目目标仅仅是为了离线识别

**Comment by Initial-heart-1** [comment]
理解，如果需要进一步优化模型的话，虽然很难提供算力支持，但样本我可以发动用户整个w级的（
